---

- name: Get VM details
  hosts: localhost
  connection: local
  vars_files:
    - "./envs/{{ env }}"
    - "./envs/{{ deploymenttype }}"
  tasks:
  - name: Get the VMs we need to configure and add as hostgroups
    ansible.builtin.include_tasks: "get_vms.yml"

# Configure VMs at Azure level
- name: Get VM details
  hosts: localhost
  connection: local
  vars_files:
    - "./envs/{{ env }}"
    - "./envs/{{ deploymenttype }}"
  tasks:
  - include_role:
      name: configure_azure_vms

# Configure VMs at OS level
- name: Configure VMs at OS level
  hosts: windows
  tasks:
  - include_role:
      name: configure_vms_os