
# - name: Get the VMs we need to configure and add as hostgroups
#   ansible.builtin.include_tasks: "get_vms.yml"

- name: All hosts - hostvars
  debug:
    msg: "Host added: {{ item }}, Resource Group: {{ hostvars[item].resourceGroupName }}"
  loop: "{{ groups['all'] | default([]) }}"

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html
- name: Configure any required disks
  ansible.builtin.include_tasks: "setup_vm_disks.yml"
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['all']}}"
