---
- hosts: all
  tasks:
    # Debian and Ubuntu
    - name: Debian and Ubuntu OS Upgrade
      ansible.builtin.apt:
        upgrade: yes
      when: ansible_distribution == 'Ubuntu'
    - name: Install snapd
      ansible.builtin.package:
        name: snapd
        state: present
    - name: Install Microk8s
      community.general.snap:
        name: microk8s
        classic: true
      register: multipass
    - name: Set up users
      ansible.builtin.shell:
        cmd: |
          usermod -a -G microk8s iain
          chown -f -R iain ~/.kube
    - name: Set up users
      ansible.builtin.shell:
        cmd: newgrp microk8s
      become: yes
      become_user: iain
