receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/jaeger:  # Use otlp exporter for Jaeger
    endpoint: "jaeger:4317"  # Jaeger's OTLP gRPC endpoint
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]  # Reference the otlp exporter for Jaeger
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]