---
- name: Install and configure Octopus Tentacle on Windows
  hosts: windows
  gather_facts: yes

  # See windows group_vars for per default host roles and environments, override in hosts file per host
  vars:
    octopus_server_url: "http://192.168.1.239"
    octopus_server_thumbprint: "2BFB75FA3F20C034CB91920D59A6E39D59BBDBA6"
    tentacle_instance_name: "Tentacle"
    tentacle_name: "{{ inventory_hostname }}"
    tentacle_port: "10933"
    tentacle_dir: "C:\\Octopus\\Tentacle"
    tentacle_config: "C:\\Octopus\\Tentacle\\Tentacle.config"
    tentacle_app_dir: "C:\\Octopus\\Applications"
    server_comms_port: "10943"
    # Provide these as part of install
    # octopus_api_key: "API-5PM3FUISORY9PTIIKTWFSIRCJO99L83Z"

  tasks:
    - name: Assert that both octopus_api_key is defined
      assert:
        that:
          - octopus_api_key is defined
        fail_msg: "octopus_api_key must be provided."

    # Check if machine already exists in Octopus before starting installation
    - name: Get list of machines from Octopus by name
      uri:
        url: "{{ octopus_server_url }}/api/machines?name={{ tentacle_name }}"
        method: GET
        headers:
          X-Octopus-ApiKey: "{{ octopus_api_key }}"
        return_content: yes
      register: machines_response
      delegate_to: localhost

    - name: Extract machine ID
      set_fact:
        tentacle_machine_id: "{{ (machines_response.json.Items|default([])|first).Id if machines_response.json.TotalResults > 0 else None }}"
      delegate_to: localhost

    - name: Fail if the machine already exists in Octopus
      fail:
        msg: "Machine named {{ tentacle_name }} already found in Octopus. Quitting"
      when: tentacle_machine_id
      delegate_to: localhost

    # Machine does not already exist, can install Tentacle and register with Octopus
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Remove the default Chocolatey source
      win_chocolatey_source:
        name: chocolatey
        state: absent

    - name: Add the Nexus repository as a new source
      win_chocolatey_source:
        name: nexus
        source: http://192.168.1.239:8081/repository/chocolatey-group/
        state: present

    - name: Install Octopus Deploy Tentacle via Chocolatey
      win_chocolatey:
        name: octopusdeploy.tentacle
        state: present

    - name: Ensure Tentacle directory exists
      win_file:
        path: "{{ tentacle_dir }}"
        state: directory

    - name: Create Tentacle instance
      win_command: '"C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe" create-instance --instance "{{ tentacle_instance_name }}" --config "{{ tentacle_config }}"'

    - name: Generate a new certificate for the Tentacle
      win_command: '"C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe" new-certificate --instance "{{ tentacle_instance_name }}"'
      register: certificate_creation
      ignore_errors: yes

    # Need to do funkier stuff if the certificate creation fails
    - name: Include Specific Certificate Creation Tasks if the Certificate Creation Fails
      include_tasks: CertificateCreationFailed.yml
      when: certificate_creation is failed

    - name: Reset Tentacle trust
      win_command: '"C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe" configure --instance "{{ tentacle_instance_name }}" --reset-trust'

    - name: Configure Tentacle directories and port
      win_command: '"C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe" configure --instance "{{ tentacle_instance_name }}" --home "C:\Octopus" --app "{{ tentacle_app_dir }}" --port "{{ tentacle_port }}"'

    - name: Register Tentacle with multiple environments and roles in one go
      win_command: >
        "C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe" register-with
        --instance "{{ tentacle_instance_name }}"
        --server "{{ octopus_server_url }}"
        --name "{{ tentacle_name }}"
        {% for env in tentacle_environments %}
        --environment "{{ env }}"
        {% endfor %}
        {% for role in tentacle_roles %}
        --role "{{ role }}"
        {% endfor %}
        --server-comms-port "{{ server_comms_port }}"
        --apiKey "{{ octopus_api_key }}"
        --comms-style TentaclePassive

    - name: Install and start the Tentacle service
      win_command: '"C:\Program Files\Octopus Deploy\Tentacle\Tentacle.exe" service --install --start --instance "{{ tentacle_instance_name }}"'

    - name: Ensure the service is started
      win_service:
        name: "OctopusDeploy Tentacle"
        state: started