version: '3'

tasks:
  platforms: [windows]
  test:
    cmds:
      - echo 'Running command on Windows'

  build-image:
    cmds:
      - powershell -command 'if (Test-Path 'output-windows') { Remove-Item -Path 'output-windows' -Recurse -Force }'
      - packer build ./windows.pkr.hcl
      - qemu-img convert -f vmdk -O qcow2  ./output-windows/win2022-disk001.vmdk D:/QCOW/windows-2022.qcow2

  create-vm:
    cmds:
      - kubectl apply  -f kubevirt_win2022_pvc.yml
      - kubectl apply  -f kubevirt_win2022_dv.yml
      - kubectl apply  -f kubevirt_win2022_vm.yml

  status-vm:
    cmds:
      - kubectl describe vm vm1

  vnc-vm:
    cmds:
      - virtctl vnc vm1

  stop-vm:
    cmds:
      - virtctl stop vm1

  start-vm:
    cmds:
      - virtctl start vm1

  delete-vm:
    cmds:
      - kubectl delete  -f kubevirt_win2022_pvc.yml
      - kubectl delete  -f kubevirt_win2022_dv.yml
      - kubectl delete  -f kubevirt_win2022_vm.yml
