---
- hosts: all
  vars:
    namespace_name: "arc-systems"
  tasks:
    # Basic OS Setup
    - name: Update apt repository cache
      apt:
        update_cache: yes
    - name: Ubuntu OS Upgrade
      ansible.builtin.apt:
        upgrade: yes
    - name: Install prerequisites
      apt:
        name:
          - curl
          - apt-transport-https
          - gnupg
          - software-properties-common
        state: present
    - name: Install snapd
      ansible.builtin.package:
        name: snapd
        state: present
    - name: Install Kubectl
      community.general.snap:
        name: kubectl
        classic: true
    - name: Install Helm
      community.general.snap:
        name: helm
        classic: true
    - name: Install Docker
      community.general.snap:
        name: docker
        classic: true


    # Install KIND
    - name: Check if kind is already installed
      stat:
        path: /usr/local/bin/kind
      register: kind_check

    - name: Download kind if not already installed (x86_64 architecture)
      when: kind_check.stat.exists == false
      shell: |
        [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.24.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create kind cluster configuration file with dynamic IP
      copy:
        dest: /root/kind-config-github.yaml
        content: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          name: github
          networking:
            ipFamily: ipv4
            apiServerAddress: {{ ansible_default_ipv4.address }}
            apiServerPort: 45001

    - name: Check if Kind cluster 'github' exists
      command: kind get clusters
      register: kind_clusters
      changed_when: false

    - name: Create Kind cluster if it doesn't exist
      when: "'github' not in kind_clusters.stdout"
      command: kind create cluster --name github --config /root/kind-config-github.yaml

    # ========================================================================
    # Install the gha-runner-scale-set-controller Helm chart manually