# Version 0.2
# http://tecadmin.net/install-zabbix-network-monitoring-on-centos-rhel-and-fedora/
FROM centos:centos7
MAINTAINER Iain Black
ENV REFRESHED_AT 2015-03-19

# Install Zabbix release packages.
RUN yum install -y http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm && \
                   yum update -y && \
                   yum -y install \
                          monit \
                          nmap  \
                          traceroute \
                          wget  \
                          nano \
                          zabbix-agent \
                          zabbix-server \
                          zabbix-server-mysql \
                          zabbix-agent \
                          zabbix-java-gateway \
                          zabbix-sender && \
                    yum clean all

EXPOSE 10051 10052

