# Version 0.2
# http://tecadmin.net/install-zabbix-network-monitoring-on-centos-rhel-and-fedora/
FROM centos:centos7
MAINTAINER Iain Black
ENV REFRESHED_AT 2015-03-19
# Do this or get a "Failed to get D-Bus connection: Operation not permitted" message
#ENV container=docker

# Install Zabbix release packages.
RUN yum install -y http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm && \
                   yum update -y && \
                   yum -y install \
                          supervisor \
                          which \ 
                          monit \
                          nmap  \
                          traceroute \
                          wget  \
                          nano \
                          httpd \
                          httpd-devel \
                          mariadb \
                          mariadb-server \
                          php \
                          php-cli \
                          php-common \
                          php-devel \
                          php-pear \
                          php-gd \
                          php-mbstring \
                          php-mysql \
                          php-xml \
                          zabbix-agent \
                          zabbix-server \
                          zabbix-server-mysql \
                          zabbix-web \
                          zabbix-web-mysql \
                          zabbix-agent \
                          zabbix-java-gateway \
                          zabbix-sender && \
                    yum clean all

#Amend the php config file
RUN sed -i -e 's/# php_value date.timezone Europe\/Riga/php_value date.timezone Europe\/Riga/g'  /etc/httpd/conf.d/zabbix.conf

# http://www.bluepiccadilly.com/2011/12/creating-mysql-database-and-user-command-line-and-bash-script-automate-process
COPY ./createdb.sh /root/createdb.sh
RUN chmod +x /root/createdb.sh
#Need to figure out MYSQL issue first
#CMD ["/root/createdb.sh", "zabbix", "zabbix", "zabbix"]

# Get MYSQL running without systemd 
RUN yum -y install initscripts
WORKDIR /usr
RUN echo "bind-address=0.0.0.0" >> /etc/my.cnf
RUN /usr/bin/mysql_install_db --datadir="/var/lib/mysql" --user=mysql
RUN /usr/bin/mysqld_safe --datadir="/var/lib/mysql" --socket="/var/lib/mysql/mysql.sock" --user=mysql  >/dev/null 2>&1 &
RUN /usr/bin/mysqladmin -u root password SOMEPASSWORD
CMD tail -f /var/log/mariadb/mariadb.log
EXPOSE 3306

EXPOSE 10051 10052 80 2812

