- name: Format and attach any disks
  win_shell: |
    Write-Output "Initialising Disks"
    $disks = Get-Disk | Where partitionstyle -eq "raw" | sort number

    # E to Y
    $letters = 69..89 | ForEach-Object { [char]$_ }
    $count = 0
    $labels = "Data","Logs","Other1","Other2","Other3","Other4","Other5"

    foreach ($disk in $disks) {
        $driveLetter = $letters[$count].ToString()
        #First pass try to find if a CD drive exists as E:. If it does move it out the way
        if ($count -eq "0") {
            $drive = Get-WmiObject win32_volume -filter 'DriveLetter = "E:"'
            if ($drive.DriveType -eq "5") {
                Write-Output "E: exists as a CD drive. Changing it to a Z:"
                $drive.DriveLetter = "Z:"
                $drive.Put()
            }
        }
        Write-Output "Trying to create a disk with letter $driveLetter"
        $drive = Get-WmiObject win32_volume -filter "DriveLetter = ""$($driveLetter):"""
        # Drive letter does not exist already, create and map to it
        if ($drive -eq $null) {
            $disk | 
            Initialize-Disk -PartitionStyle MBR -PassThru |
            New-Partition -UseMaximumSize -DriveLetter $driveLetter |
            Format-Volume -FileSystem NTFS -NewFileSystemLabel $labels[$count] -Confirm:$false -Force
            $count++
        }
        else {
            Write-Output "Drive letter $driveLetter already exists. Going to next letter to map disk"
            $count++
        }
    }
