- name: All hosts - hostvars
  debug:
    msg: "Host added: {{ item }}, Resource Group: {{ hostvars[item].resourceGroupName }}"
  loop: "{{ groups['all'] | default([]) }}"

###########################################
# Format Disks
- name: Format Disks
  ansible.builtin.include_tasks: "format_disks.yml"

############################################
# Local Admins
- name: Configure Local Admins
  ansible.builtin.include_tasks: "local_admins.yml"

###########################################
# Octopus Deploy Tentacle Installation
- name: Check if Octopus Tentacle service is already installed
  win_service:
    name: OctopusDeploy Tentacle
  register: is_tentacle_installed
  ignore_errors: true  # Ensure the playbook continues even if the service is not found

- name: Install Octopus Tentacle (if not already installed)
  block:
    - name: Include tasks to install Octopus Tentacle
      ansible.builtin.include_tasks: "install_octopus_tentacle.yml"
  when: not (is_tentacle_installed.exists is defined and is_tentacle_installed.exists)


#####################################################################################################
# Octopus Deploy Tentacle Registration - If not already registered (logic in registration script)
- name: Register Octopus Tentacle
  include_tasks: register_octopus_tentacle.yml
  tags: ["register-octopus-tentacles"]
