apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: rundeck
  name: rundeck
spec:
  ports:
    - name: "4440"
      port: 4440
      targetPort: 4440
  selector:
    io.kompose.service: rundeck
