apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: rundeck
  name: rundeck
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rundeck
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: rundeck
    spec:
      containers:
        - image: rundeck/rundeck:SNAPSHOT
          name: rundeck
          ports:
            - containerPort: 4440
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /home/rundeck/server/data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
