---
- name: Create Multipass VMs for a MicroK8S cluster
  hosts: windows

  tasks:
  - name: Read MicroK8S cluster node VM configuration from file
    include_vars:
      file: microk8s-instances.yml
      name: microk8sinstances
  - name: Create the MicroK8S cluster Instances
    include_tasks: delete-and-create-new-vm-tasks.yml
    vars:
      vmname: "{{ item.key }}"
      vmcreationparams: "{{ item.value }}"
      delete_if_exists: false
    loop: "{{ microk8sinstances | dict2items }}"
  - name: Add to hosts list for configuration
    include_tasks: add-to-hosts-list.yml
    vars:
      vmname: "{{ item.key }}"
      vmcreationparams: "{{ item.value }}"
      delete_if_exists: false
    loop: "{{ microk8sinstances | dict2items }}"