# Version 0.2
# http://tecadmin.net/install-zabbix-network-monitoring-on-centos-rhel-and-fedora/
FROM centos:centos7
MAINTAINER Iain Black
ENV REFRESHED_AT 2015-03-19

# Install Zabbix release packages.
RUN yum install -y http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm && \
                   yum update -y && \
                   yum -y install \
                          httpd \
                          httpd-devel \
                          php \
                          php-cli \
                          php-common \
                          php-devel \
                          php-pear \
                          php-gd \
                          php-mbstring \
                          php-mysql \
                          php-xml \
                          zabbix-web \
                          zabbix-web-mysql \
                  yum clean all

#Amend the php config file
RUN sed -i -e 's/# php_value date.timezone Europe\/Riga/php_value date.timezone Europe\/Riga/g'  /etc/httpd/conf.d/zabbix.conf

EXPOSE 80

ADD run-apache.sh /run-apache.sh
RUN chmod -v +x /run-apache.sh

CMD ["/run-apache.sh"]