---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: hello-go
    microk8s_cmd: '/snap/bin/microk8s'

  pre_tasks:
    - name: Check MicroK8s status
      ansible.builtin.shell:
        cmd: "{{ microk8s_cmd }} status"
      register: microk8s_status
      changed_when: false
      ignore_errors: true

    - name: Start MicroK8s if it is not running
      ansible.builtin.shell:
        cmd: "{{ microk8s_cmd }} start"
      when: "not microk8s_status.stdout or 'microk8s is running' not in microk8s_status.stdout"

# kubectl create namespace argocd
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# kubectl port-forward svc/argocd-server -n argocd 8080:443
# argocd admin initial-password -n argocd
# argocd login localhost:8080