version: '3.9'
# https://gruchalski.com/posts/2020-09-03-keycloak-with-docker-compose/
services:
  keycloak:
    container_name: local_keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    restart: unless-stopped
    networks:
      - local-keycloak
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data/:rw

volumes:
  keycloak_data:

networks:
  local-keycloak: