version: '3.9'
# https://gruchalski.com/posts/2020-09-03-keycloak-with-docker-compose/
services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - local-keycloak
    env_file:
     -  stack.env

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    image: jboss/keycloak:11.0.2
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak
    env_file:
      -  stack.env

networks:
  local-keycloak: