---
- name: Test Octopus Access from Ansible Host
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    octopus_server_url: "http://192.168.1.239"
    tentacle_instance_name: "Tentacle"
    tentacle_name: "{{ inventory_hostname }}"
    tentacle_port: "10933"
    # Provide these as part of install
    # octopus_api_key: "API-5PM3FUISORY9PTIIKTWFSIRCJO99L83Z"

  tasks:
    - name: Get list of machines from Octopus by name
      uri:
        url: "{{ octopus_server_url }}/api/machines?name={{ tentacle_name }}"
        method: GET
        headers:
          X-Octopus-ApiKey: "{{ octopus_api_key }}"
        return_content: yes
      register: machines_response
      delegate_to: localhost
      connection: local

- name: Test OS Access
  hosts: windows
  gather_facts: yes

  tasks:
    - name: Ensure directory exists
      win_file:
        path: "c:/Temp"
        state: directory