---
- hosts: all
  tasks:

    - name: Set TERM environment variable
      shell: export TERM=xterm
      environment:
        TERM: xterm
        
    - name: Execute the script
      shell: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"