---
- hosts: all
  tasks:
    # https://github.com/UntouchedWagons/Ubuntu-CloudInit-Docs
    - name: Copy the script to the remote host
      copy:
        src: ./scripts/create-ubuntu-2404-template.sh
        dest: /tmp/create-ubuntu-2404-template.sh
        mode: '0755'  # Ensure the script is executable

    - name: Execute the script
      shell: /tmp/create-ubuntu-2404-template.sh