# kubectl get service -n webtop -o wide
# kubectl delete namespace webtop
apiVersion: v1
kind: Namespace
metadata:
  name: webtop
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webtop-service
  name: webtop-service
  namespace: webtop
spec:
  ports:
    - name: 3000-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: webtop-service
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webtop
    app: webtop-service
  name: webtop
  namespace: webtop
spec:
  containers:
    - image: lsiodev/webtop:ubuntu-kde
      name: webtop
      ports:
        - containerPort: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always