# https://blog.hypriot.com/post/run-your-own-github-like-service-with-docker/
# docker build -t gogs .
# docker run -d -p 8022:22 -p 3000:3000 -v e:/project/gogs/data/:c:/data/ -v e:/project/gogs/gogs-repositories/:C:/gogs-repositories/ -v e:/project/gogs/logs/:C:/gogs/log/ gogs
# mkdir project
# mkdir testproj
# docker run -d -p 8080:80 -p 4430:443 -p 8111:8111 -v c:/teamcity/:C:/ProgramData/JetBrains/TeamCity/ teamcity

FROM microsoft/windowsservercore
EXPOSE 22
EXPOSE 3000

COPY . /
WORKDIR /

#On container launch, unzip gogs and then copy app.ini to folder and start web service
SHELL ["powershell"]
#Gogs need git installed. Internally assume file is in container but if running without the git installer present then use choco
RUN if (Test-Path .\Installer\Git-2.13.0-64-bit.exe) { .\Installer\Git-2.13.0-64-bit.exe /VERYSILENT /norestart } else { iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); choco install git -y }
RUN New-Item c:\gogsapp\gogs -type directory -Force
RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices' -Name 'G:' -Value '\??\c:\gogsapp\gogs' -Type String
CMD .\dockerfile.ps1
